require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ContentAssetsController do

  def mock_content_asset(stubs={})
    @mock_content_asset ||= mock_model(ContentAsset, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all content_assets as @content_assets" do
      ContentAsset.stub(:all) { [mock_content_asset] }
      get :index
      assigns(:content_assets).should eq([mock_content_asset])
    end
  end

  describe "GET show" do
    it "assigns the requested content_asset as @content_asset" do
      ContentAsset.stub(:find).with("37") { mock_content_asset }
      get :show, :id => "37"
      assigns(:content_asset).should be(mock_content_asset)
    end
  end

  describe "GET new" do
    it "assigns a new content_asset as @content_asset" do
      ContentAsset.stub(:new) { mock_content_asset }
      get :new
      assigns(:content_asset).should be(mock_content_asset)
    end
  end

  describe "GET edit" do
    it "assigns the requested content_asset as @content_asset" do
      ContentAsset.stub(:find).with("37") { mock_content_asset }
      get :edit, :id => "37"
      assigns(:content_asset).should be(mock_content_asset)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created content_asset as @content_asset" do
        ContentAsset.stub(:new).with({'these' => 'params'}) { mock_content_asset(:save => true) }
        post :create, :content_asset => {'these' => 'params'}
        assigns(:content_asset).should be(mock_content_asset)
      end

      it "redirects to the created content_asset" do
        ContentAsset.stub(:new) { mock_content_asset(:save => true) }
        post :create, :content_asset => {}
        response.should redirect_to(content_asset_url(mock_content_asset))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved content_asset as @content_asset" do
        ContentAsset.stub(:new).with({'these' => 'params'}) { mock_content_asset(:save => false) }
        post :create, :content_asset => {'these' => 'params'}
        assigns(:content_asset).should be(mock_content_asset)
      end

      it "re-renders the 'new' template" do
        ContentAsset.stub(:new) { mock_content_asset(:save => false) }
        post :create, :content_asset => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested content_asset" do
        ContentAsset.stub(:find).with("37") { mock_content_asset }
        mock_content_asset.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :content_asset => {'these' => 'params'}
      end

      it "assigns the requested content_asset as @content_asset" do
        ContentAsset.stub(:find) { mock_content_asset(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:content_asset).should be(mock_content_asset)
      end

      it "redirects to the content_asset" do
        ContentAsset.stub(:find) { mock_content_asset(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(content_asset_url(mock_content_asset))
      end
    end

    describe "with invalid params" do
      it "assigns the content_asset as @content_asset" do
        ContentAsset.stub(:find) { mock_content_asset(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:content_asset).should be(mock_content_asset)
      end

      it "re-renders the 'edit' template" do
        ContentAsset.stub(:find) { mock_content_asset(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested content_asset" do
      ContentAsset.stub(:find).with("37") { mock_content_asset }
      mock_content_asset.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the content_assets list" do
      ContentAsset.stub(:find) { mock_content_asset }
      delete :destroy, :id => "1"
      response.should redirect_to(content_assets_url)
    end
  end

end
